apiVersion: v1
kind: ConfigMap
metadata:
  name: study-nginx
  namespace: app
data:
  default.conf: |
    server {
        listen       8080;
        server_name  _;

        root   /git/current;
        index  index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location ~* \.md$ {
            default_type text/markdown;
            charset utf-8;
        }
    }
