apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: study
  namespace: cicd
spec:
  project: default
  source:
    repoURL: https://github.com/ggingggang/study.git
    targetRevision: main
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
